---
title: "R Notebook"
output: 
  html_document:
    keep_md: true
---


```{r}

library(reshape2)
library(tidyverse)
library(wbstats)
library(data.table)
library(ggthemes)
library(plotly)
library(psych)
library(highcharter)
library(quantmod)
library(TTR)
library(dplyr)
library(tidyr)

```

#Data
```{r}

population <- wb('SP.POP.TOTL', country = 'countries_only') %>%
  mutate(date = as.numeric(date), value = round(value / 1000000, 2), indicator = 'Population') %>%
  select(-indicatorID)

gdp <- wb('NY.GDP.PCAP.CD', country = 'countries_only') %>%
  mutate(date = as.numeric(date), value = round(value, 2), indicator = 'GDP per Capita') %>%
  select(-indicatorID)

lifeexpectancy <- wb('SP.DYN.LE00.IN', country = 'countries_only') %>%
  mutate(date = as.numeric(date), value = round(value, 2), indicator = 'Life Expectancy') %>%
  select(-indicatorID)

bind_rows(gdp, lifeexpectancy, population) %>% tidyr::pivot_wider(names_from = 'indicator', values_from = 'value') %>%
  na.omit()
```

#Line chat - GDP time series
```{r}

line_data <- gdp %>% filter(iso3c == 'CHL')
line_data2 <- gdp %>% filter(iso3c == 'PER')

ggplot() +
  geom_line(data = line_data,
                aes(x = date,
                y = value),
              color = 'darkblue',
              size = 1) +
  
   geom_line(data = line_data2,
                aes(x = date,
                y = value),
              color = 'darkred',
              size = 1) +
  
  labs(title = 'GDP per Capita (Current USD)',
       x = 'Date',
       y = 'Current USD',
       subtitle = paste('From ', min(line_data$date), ' to ', max(line_data$date), sep = '')) +
  ggthemes::theme_economist_white()

```


